BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TYPE public.huawei_sync_job_status AS ENUM (
  'pending', 'running', 'success', 'partial', 'failed', 'retrying', 'dead_letter'
);
CREATE TYPE public.huawei_period_type AS ENUM ('hour', 'day', 'month', 'year');

CREATE OR REPLACE FUNCTION public.solar_has_access()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users
    WHERE auth_user_id = auth.uid()
      AND role IN ('super_admin', 'manager_sale', 'manager_marketing', 'engineer')
  );
$$;

CREATE OR REPLACE FUNCTION public.solar_is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users
    WHERE auth_user_id = auth.uid() AND role = 'super_admin'
  );
$$;

CREATE TABLE public.huawei_integrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT 'Huawei SmartPVMS SG5',
  base_url text NOT NULL CHECK (base_url ~ '^https://'),
  secret_prefix text NOT NULL DEFAULT 'HUAWEI',
  enabled boolean NOT NULL DEFAULT false,
  sync_mode text NOT NULL DEFAULT 'pilot' CHECK (sync_mode IN ('pilot', 'limited', 'full')),
  pilot_plant_limit integer NOT NULL DEFAULT 5 CHECK (pilot_plant_limit > 0),
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error_code text,
  last_error_message text,
  session_lock_owner text,
  session_lock_until timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.huawei_api_sessions (
  integration_id uuid PRIMARY KEY REFERENCES public.huawei_integrations(id) ON DELETE CASCADE,
  xsrf_token text NOT NULL,
  expires_at timestamptz NOT NULL,
  refreshed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.huawei_plants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL REFERENCES public.huawei_integrations(id) ON DELETE CASCADE,
  plant_code text NOT NULL,
  plant_name text NOT NULL,
  plant_address text,
  province text,
  latitude numeric,
  longitude numeric,
  capacity_kwp numeric,
  grid_connection_date timestamptz,
  time_zone text NOT NULL DEFAULT 'Asia/Bangkok',
  health_state integer,
  enabled_for_sync boolean NOT NULL DEFAULT false,
  visible_in_dashboard boolean NOT NULL DEFAULT false,
  source_updated_at timestamptz,
  last_synced_at timestamptz,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (integration_id, plant_code)
);

CREATE TABLE public.huawei_devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL REFERENCES public.huawei_integrations(id) ON DELETE CASCADE,
  plant_id uuid NOT NULL REFERENCES public.huawei_plants(id) ON DELETE CASCADE,
  huawei_device_id text,
  dev_dn text,
  dev_type_id integer NOT NULL,
  esn text,
  device_name text,
  model text,
  software_version text,
  device_status integer,
  enabled_for_sync boolean NOT NULL DEFAULT true,
  last_synced_at timestamptz,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (integration_id, huawei_device_id),
  UNIQUE (integration_id, dev_dn)
);

CREATE TABLE public.huawei_plant_customer_links (
  plant_id uuid PRIMARY KEY REFERENCES public.huawei_plants(id) ON DELETE CASCADE,
  customer_service_id integer NOT NULL REFERENCES public.customer_services(id) ON DELETE RESTRICT,
  match_status text NOT NULL DEFAULT 'confirmed' CHECK (match_status IN ('suggested', 'confirmed')),
  confirmed_by uuid REFERENCES auth.users(id),
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_service_id)
);

CREATE TABLE public.huawei_plant_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_id uuid NOT NULL REFERENCES public.huawei_plants(id) ON DELETE CASCADE,
  sampled_at timestamptz NOT NULL,
  current_power_kw numeric,
  daily_energy_kwh numeric,
  monthly_energy_kwh numeric,
  lifetime_energy_kwh numeric,
  daily_feed_in_kwh numeric,
  daily_consumption_kwh numeric,
  daily_income numeric,
  lifetime_income numeric,
  health_state integer,
  quality_flags text[] NOT NULL DEFAULT '{}',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (plant_id, sampled_at)
);

CREATE TABLE public.huawei_device_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id uuid NOT NULL REFERENCES public.huawei_devices(id) ON DELETE CASCADE,
  sampled_at timestamptz NOT NULL,
  active_power_kw numeric,
  reactive_power_kvar numeric,
  daily_energy_kwh numeric,
  lifetime_energy_kwh numeric,
  voltage_v numeric,
  current_a numeric,
  frequency_hz numeric,
  temperature_c numeric,
  efficiency_percent numeric,
  soc_percent numeric,
  soh_percent numeric,
  charge_power_kw numeric,
  discharge_power_kw numeric,
  run_state text,
  quality_flags text[] NOT NULL DEFAULT '{}',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (device_id, sampled_at)
);

CREATE TABLE public.huawei_plant_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_id uuid NOT NULL REFERENCES public.huawei_plants(id) ON DELETE CASCADE,
  period_type public.huawei_period_type NOT NULL,
  period_start timestamptz NOT NULL,
  period_end timestamptz,
  plant_local_date date,
  yield_kwh numeric,
  pv_yield_kwh numeric,
  inverter_yield_kwh numeric,
  consumption_kwh numeric,
  feed_in_kwh numeric,
  grid_purchase_kwh numeric,
  self_consumption_kwh numeric,
  charge_kwh numeric,
  discharge_kwh numeric,
  peak_power_kw numeric,
  performance_ratio numeric,
  revenue numeric,
  quality_flags text[] NOT NULL DEFAULT '{}',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (plant_id, period_type, period_start)
);

CREATE TABLE public.huawei_device_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id uuid NOT NULL REFERENCES public.huawei_devices(id) ON DELETE CASCADE,
  period_type public.huawei_period_type NOT NULL,
  period_start timestamptz NOT NULL,
  period_end timestamptz,
  plant_local_date date,
  yield_kwh numeric,
  charge_kwh numeric,
  discharge_kwh numeric,
  peak_power_kw numeric,
  quality_flags text[] NOT NULL DEFAULT '{}',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ingested_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (device_id, period_type, period_start)
);

CREATE TABLE public.huawei_alarm_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL REFERENCES public.huawei_integrations(id) ON DELETE CASCADE,
  plant_id uuid REFERENCES public.huawei_plants(id) ON DELETE SET NULL,
  device_id uuid REFERENCES public.huawei_devices(id) ON DELETE SET NULL,
  station_code text,
  esn text,
  alarm_id text NOT NULL,
  cause_id text NOT NULL DEFAULT '',
  raised_at timestamptz NOT NULL,
  alarm_name text,
  alarm_cause text,
  repair_suggestion text,
  severity integer CHECK (severity BETWEEN 1 AND 4),
  alarm_type text,
  status text NOT NULL DEFAULT 'active',
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE NULLS NOT DISTINCT (integration_id, station_code, esn, alarm_id, cause_id, raised_at)
);

CREATE TABLE public.huawei_tariffs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plant_id uuid NOT NULL REFERENCES public.huawei_plants(id) ON DELETE CASCADE,
  name text NOT NULL,
  currency text NOT NULL DEFAULT 'THB',
  import_rate_per_kwh numeric NOT NULL CHECK (import_rate_per_kwh >= 0),
  export_rate_per_kwh numeric CHECK (export_rate_per_kwh >= 0),
  valid_from date NOT NULL,
  valid_to date,
  confirmed_by uuid REFERENCES auth.users(id),
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (valid_to IS NULL OR valid_to >= valid_from),
  UNIQUE (plant_id, valid_from)
);

CREATE TABLE public.huawei_sync_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL REFERENCES public.huawei_integrations(id) ON DELETE CASCADE,
  job_type text NOT NULL CHECK (job_type IN (
    'discover_plants', 'discover_devices', 'plant_realtime', 'device_realtime',
    'active_alarms', 'plant_report', 'device_report', 'device_history', 'data_quality'
  )),
  entity_id uuid,
  scope jsonb NOT NULL DEFAULT '{}'::jsonb,
  status public.huawei_sync_job_status NOT NULL DEFAULT 'pending',
  priority integer NOT NULL DEFAULT 100,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 5,
  scheduled_at timestamptz NOT NULL DEFAULT now(),
  claimed_at timestamptz,
  claimed_by text,
  started_at timestamptz,
  finished_at timestamptz,
  last_error_code text,
  last_error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX huawei_sync_jobs_dedupe_active
  ON public.huawei_sync_jobs (integration_id, job_type, COALESCE(entity_id, '00000000-0000-0000-0000-000000000000'::uuid), md5(scope::text))
  WHERE status IN ('pending', 'running', 'retrying');

CREATE TABLE public.huawei_sync_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL REFERENCES public.huawei_integrations(id) ON DELETE CASCADE,
  job_id uuid REFERENCES public.huawei_sync_jobs(id) ON DELETE SET NULL,
  job_type text NOT NULL,
  status public.huawei_sync_job_status NOT NULL,
  endpoint text,
  http_status integer,
  fail_code text,
  records_received integer NOT NULL DEFAULT 0,
  records_written integer NOT NULL DEFAULT 0,
  duration_ms integer,
  error_message text,
  cursor jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);

CREATE TABLE public.huawei_data_quality_issues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL REFERENCES public.huawei_integrations(id) ON DELETE CASCADE,
  plant_id uuid REFERENCES public.huawei_plants(id) ON DELETE CASCADE,
  device_id uuid REFERENCES public.huawei_devices(id) ON DELETE CASCADE,
  issue_key text NOT NULL,
  issue_type text NOT NULL CHECK (issue_type IN (
    'stale_plant', 'missing_intervals', 'future_timestamp', 'counter_reset', 'invalid_metric'
  )),
  severity text NOT NULL DEFAULT 'warning' CHECK (severity IN ('info', 'warning', 'critical')),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  UNIQUE (integration_id, issue_key)
);

CREATE INDEX huawei_plants_name_idx ON public.huawei_plants (plant_name);
CREATE INDEX huawei_plants_status_idx ON public.huawei_plants (health_state, visible_in_dashboard);
CREATE INDEX huawei_devices_plant_idx ON public.huawei_devices (plant_id, dev_type_id);
CREATE INDEX huawei_plant_samples_time_idx ON public.huawei_plant_samples (plant_id, sampled_at DESC);
CREATE INDEX huawei_device_samples_time_idx ON public.huawei_device_samples (device_id, sampled_at DESC);
CREATE INDEX huawei_plant_reports_time_idx ON public.huawei_plant_reports (plant_id, period_type, period_start DESC);
CREATE INDEX huawei_device_reports_time_idx ON public.huawei_device_reports (device_id, period_type, period_start DESC);
CREATE INDEX huawei_alarm_status_idx ON public.huawei_alarm_events (status, severity, raised_at DESC);
CREATE INDEX huawei_jobs_claim_idx ON public.huawei_sync_jobs (status, scheduled_at, priority);
CREATE INDEX huawei_runs_time_idx ON public.huawei_sync_runs (started_at DESC);
CREATE INDEX huawei_quality_open_idx ON public.huawei_data_quality_issues (resolved_at, issue_type, severity);

ALTER TABLE public.huawei_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_api_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_plants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_plant_customer_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_plant_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_device_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_plant_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_device_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_alarm_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_tariffs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_sync_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.huawei_data_quality_issues ENABLE ROW LEVEL SECURITY;

CREATE POLICY solar_read_integrations ON public.huawei_integrations FOR SELECT TO authenticated USING (solar_has_access());
CREATE POLICY solar_read_plants ON public.huawei_plants FOR SELECT TO authenticated USING (solar_has_access() AND visible_in_dashboard);
CREATE POLICY solar_read_devices ON public.huawei_devices FOR SELECT TO authenticated
  USING (solar_has_access() AND EXISTS (SELECT 1 FROM public.huawei_plants p WHERE p.id = plant_id AND p.visible_in_dashboard));
CREATE POLICY solar_read_links ON public.huawei_plant_customer_links FOR SELECT TO authenticated USING (solar_has_access());
CREATE POLICY solar_read_plant_samples ON public.huawei_plant_samples FOR SELECT TO authenticated
  USING (solar_has_access() AND EXISTS (SELECT 1 FROM public.huawei_plants p WHERE p.id = plant_id AND p.visible_in_dashboard));
CREATE POLICY solar_read_device_samples ON public.huawei_device_samples FOR SELECT TO authenticated
  USING (solar_has_access() AND EXISTS (
    SELECT 1 FROM public.huawei_devices d JOIN public.huawei_plants p ON p.id = d.plant_id
    WHERE d.id = device_id AND p.visible_in_dashboard
  ));
CREATE POLICY solar_read_plant_reports ON public.huawei_plant_reports FOR SELECT TO authenticated
  USING (solar_has_access() AND EXISTS (SELECT 1 FROM public.huawei_plants p WHERE p.id = plant_id AND p.visible_in_dashboard));
CREATE POLICY solar_read_device_reports ON public.huawei_device_reports FOR SELECT TO authenticated
  USING (solar_has_access() AND EXISTS (
    SELECT 1 FROM public.huawei_devices d JOIN public.huawei_plants p ON p.id = d.plant_id
    WHERE d.id = device_id AND p.visible_in_dashboard
  ));
CREATE POLICY solar_read_alarms ON public.huawei_alarm_events FOR SELECT TO authenticated USING (solar_has_access());
CREATE POLICY solar_admin_tariffs ON public.huawei_tariffs FOR ALL TO authenticated USING (solar_is_admin()) WITH CHECK (solar_is_admin());
CREATE POLICY solar_admin_links ON public.huawei_plant_customer_links FOR ALL TO authenticated USING (solar_is_admin()) WITH CHECK (solar_is_admin());
CREATE POLICY solar_admin_jobs ON public.huawei_sync_jobs FOR SELECT TO authenticated USING (solar_is_admin());
CREATE POLICY solar_admin_runs ON public.huawei_sync_runs FOR SELECT TO authenticated USING (solar_has_access());
CREATE POLICY solar_read_quality ON public.huawei_data_quality_issues FOR SELECT TO authenticated USING (solar_has_access());

CREATE OR REPLACE FUNCTION public.solar_claim_sync_job(p_worker text)
RETURNS SETOF public.huawei_sync_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH next_job AS (
    SELECT id FROM public.huawei_sync_jobs
    WHERE status IN ('pending', 'retrying') AND scheduled_at <= now()
    ORDER BY priority ASC, scheduled_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
  )
  UPDATE public.huawei_sync_jobs j
  SET status = 'running', claimed_at = now(), claimed_by = p_worker,
      started_at = now(), attempts = attempts + 1, updated_at = now()
  FROM next_job
  WHERE j.id = next_job.id
  RETURNING j.*;
END;
$$;

CREATE OR REPLACE FUNCTION public.solar_lock_huawei_login(p_integration_id uuid, p_owner text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_locked boolean;
BEGIN
  UPDATE huawei_integrations
  SET session_lock_owner = p_owner, session_lock_until = now() + interval '45 seconds'
  WHERE id = p_integration_id
    AND (session_lock_until IS NULL OR session_lock_until < now() OR session_lock_owner = p_owner)
  RETURNING true INTO v_locked;
  RETURN COALESCE(v_locked, false);
END;
$$;

CREATE OR REPLACE FUNCTION public.solar_release_huawei_login(p_integration_id uuid, p_owner text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE huawei_integrations
  SET session_lock_owner = NULL, session_lock_until = NULL
  WHERE id = p_integration_id AND session_lock_owner = p_owner;
$$;

CREATE OR REPLACE FUNCTION public.solar_refresh_data_quality(p_integration_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_count integer;
BEGIN
  INSERT INTO huawei_data_quality_issues (
    integration_id, plant_id, issue_key, issue_type, severity, details, last_seen_at, resolved_at
  )
  SELECT p_integration_id, p.id, 'stale_plant:' || p.id, 'stale_plant',
    CASE WHEN max(s.sampled_at) < now() - interval '1 hour' OR max(s.sampled_at) IS NULL THEN 'critical' ELSE 'warning' END,
    jsonb_build_object('latestSampleAt', max(s.sampled_at), 'thresholdMinutes', 15),
    now(), NULL
  FROM huawei_plants p
  LEFT JOIN huawei_plant_samples s ON s.plant_id = p.id
  WHERE p.integration_id = p_integration_id AND p.enabled_for_sync
  GROUP BY p.id
  HAVING max(s.sampled_at) IS NULL OR max(s.sampled_at) < now() - interval '15 minutes'
  ON CONFLICT (integration_id, issue_key) DO UPDATE SET
    severity = excluded.severity, details = excluded.details, last_seen_at = now(), resolved_at = NULL;

  INSERT INTO huawei_data_quality_issues (
    integration_id, plant_id, issue_key, issue_type, severity, details, last_seen_at, resolved_at
  )
  SELECT p_integration_id, p.id, 'missing_intervals:' || p.id, 'missing_intervals', 'warning',
    jsonb_build_object('sampleCount24h', count(s.id), 'expectedApprox', 288),
    now(), NULL
  FROM huawei_plants p
  LEFT JOIN huawei_plant_samples s ON s.plant_id = p.id AND s.sampled_at >= now() - interval '24 hours'
  WHERE p.integration_id = p_integration_id AND p.enabled_for_sync
  GROUP BY p.id
  HAVING count(s.id) < 259
  ON CONFLICT (integration_id, issue_key) DO UPDATE SET
    details = excluded.details, last_seen_at = now(), resolved_at = NULL;

  UPDATE huawei_data_quality_issues q
  SET resolved_at = now()
  WHERE integration_id = p_integration_id AND resolved_at IS NULL
    AND (
      (issue_type = 'stale_plant' AND EXISTS (
        SELECT 1 FROM huawei_plant_samples s WHERE s.plant_id = q.plant_id
          AND s.sampled_at >= now() - interval '15 minutes'
      ))
      OR
      (issue_type = 'missing_intervals' AND (
        SELECT count(*) FROM huawei_plant_samples s WHERE s.plant_id = q.plant_id
          AND s.sampled_at >= now() - interval '24 hours'
      ) >= 259)
    );

  DELETE FROM huawei_sync_runs WHERE started_at < now() - interval '180 days';
  DELETE FROM huawei_plant_samples WHERE sampled_at < now() - interval '24 months';
  DELETE FROM huawei_device_samples WHERE sampled_at < now() - interval '24 months';
  SELECT count(*) INTO v_count FROM huawei_data_quality_issues
    WHERE integration_id = p_integration_id AND resolved_at IS NULL;
  RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.solar_get_fleet_summary(p_filters jsonb DEFAULT '{}'::jsonb)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH allowed AS (
    SELECT p.* FROM huawei_plants p
    WHERE solar_has_access() AND p.visible_in_dashboard
      AND (p_filters->>'province' IS NULL OR p.province = p_filters->>'province')
  ), latest AS (
    SELECT DISTINCT ON (s.plant_id) s.*
    FROM huawei_plant_samples s JOIN allowed p ON p.id = s.plant_id
    ORDER BY s.plant_id, s.sampled_at DESC
  ), active_alarm AS (
    SELECT count(*) count FROM huawei_alarm_events a
    JOIN allowed p ON p.id = a.plant_id WHERE a.status = 'active'
  )
  SELECT jsonb_build_object(
    'plantCount', (SELECT count(*) FROM allowed),
    'capacityKwp', COALESCE((SELECT sum(capacity_kwp) FROM allowed), 0),
    'currentPowerKw', COALESCE((SELECT sum(current_power_kw) FROM latest), 0),
    'dailyEnergyKwh', COALESCE((SELECT sum(daily_energy_kwh) FROM latest), 0),
    'healthyCount', (SELECT count(*) FROM latest WHERE health_state = 3),
    'faultyCount', (SELECT count(*) FROM latest WHERE health_state = 2),
    'offlineCount', (SELECT count(*) FROM latest WHERE health_state = 1),
    'activeAlarmCount', (SELECT count FROM active_alarm),
    'latestSampleAt', (SELECT max(sampled_at) FROM latest)
  );
$$;

CREATE OR REPLACE FUNCTION public.solar_get_plant_list(
  p_filters jsonb DEFAULT '{}'::jsonb,
  p_sort text DEFAULT 'name_asc',
  p_page integer DEFAULT 1,
  p_page_size integer DEFAULT 25
) RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH filtered AS (
    SELECT p.*, l.customer_service_id,
      s.sampled_at, s.current_power_kw, s.daily_energy_kwh, s.health_state AS latest_health_state
    FROM huawei_plants p
    LEFT JOIN huawei_plant_customer_links l ON l.plant_id = p.id
    LEFT JOIN LATERAL (
      SELECT * FROM huawei_plant_samples ps WHERE ps.plant_id = p.id ORDER BY sampled_at DESC LIMIT 1
    ) s ON true
    WHERE solar_has_access() AND p.visible_in_dashboard
      AND (
        COALESCE(p_filters->>'search', '') = ''
        OR p.plant_name ILIKE ('%' || (p_filters->>'search') || '%')
        OR p.plant_code ILIKE ('%' || (p_filters->>'search') || '%')
      )
      AND (p_filters->>'province' IS NULL OR p.province = p_filters->>'province')
      AND (p_filters->>'healthState' IS NULL OR s.health_state = (p_filters->>'healthState')::integer)
  ), ordered AS (
    SELECT * FROM filtered
    ORDER BY
      CASE WHEN p_sort = 'power_desc' THEN current_power_kw END DESC NULLS LAST,
      CASE WHEN p_sort = 'energy_desc' THEN daily_energy_kwh END DESC NULLS LAST,
      CASE WHEN p_sort = 'name_desc' THEN plant_name END DESC,
      plant_name ASC
    LIMIT LEAST(GREATEST(p_page_size, 1), 100)
    OFFSET (GREATEST(p_page, 1) - 1) * LEAST(GREATEST(p_page_size, 1), 100)
  )
  SELECT jsonb_build_object(
    'items', COALESCE((SELECT jsonb_agg(to_jsonb(o) - 'raw_payload') FROM ordered o), '[]'::jsonb),
    'total', (SELECT count(*) FROM filtered),
    'page', GREATEST(p_page, 1),
    'pageSize', LEAST(GREATEST(p_page_size, 1), 100)
  );
$$;

CREATE OR REPLACE FUNCTION public.solar_get_plant_detail(
  p_plant_id uuid, p_from timestamptz, p_to timestamptz
) RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN NOT solar_has_access() THEN NULL ELSE jsonb_build_object(
    'plant', (SELECT to_jsonb(p) - 'raw_payload' FROM huawei_plants p WHERE p.id = p_plant_id AND p.visible_in_dashboard),
    'customerLink', (SELECT to_jsonb(l) FROM huawei_plant_customer_links l WHERE l.plant_id = p_plant_id),
    'samples', COALESCE((SELECT jsonb_agg(to_jsonb(s) - 'raw_payload' ORDER BY sampled_at)
      FROM huawei_plant_samples s WHERE s.plant_id = p_plant_id AND sampled_at BETWEEN p_from AND p_to), '[]'::jsonb),
    'devices', COALESCE((SELECT jsonb_agg(to_jsonb(d) - 'raw_payload' ORDER BY device_name)
      FROM huawei_devices d WHERE d.plant_id = p_plant_id), '[]'::jsonb),
    'alarms', COALESCE((SELECT jsonb_agg(to_jsonb(a) - 'raw_payload' ORDER BY raised_at DESC)
      FROM huawei_alarm_events a WHERE a.plant_id = p_plant_id AND raised_at BETWEEN p_from AND p_to), '[]'::jsonb)
  ) END;
$$;

CREATE OR REPLACE FUNCTION public.solar_get_device_detail(
  p_device_id uuid, p_from timestamptz, p_to timestamptz
) RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN NOT solar_has_access() THEN NULL ELSE jsonb_build_object(
    'device', (SELECT to_jsonb(d) - 'raw_payload' FROM huawei_devices d WHERE d.id = p_device_id),
    'samples', COALESCE((SELECT jsonb_agg(to_jsonb(s) - 'raw_payload' ORDER BY sampled_at)
      FROM huawei_device_samples s WHERE s.device_id = p_device_id AND sampled_at BETWEEN p_from AND p_to), '[]'::jsonb),
    'alarms', COALESCE((SELECT jsonb_agg(to_jsonb(a) - 'raw_payload' ORDER BY raised_at DESC)
      FROM huawei_alarm_events a WHERE a.device_id = p_device_id AND raised_at BETWEEN p_from AND p_to), '[]'::jsonb)
  ) END;
$$;

CREATE OR REPLACE FUNCTION public.solar_get_alarm_summary(p_filters jsonb DEFAULT '{}'::jsonb)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH filtered AS (
    SELECT a.*, p.plant_name, d.device_name
    FROM huawei_alarm_events a
    LEFT JOIN huawei_plants p ON p.id = a.plant_id
    LEFT JOIN huawei_devices d ON d.id = a.device_id
    WHERE solar_has_access()
      AND (p_filters->>'status' IS NULL OR a.status = p_filters->>'status')
      AND (p_filters->>'severity' IS NULL OR a.severity = (p_filters->>'severity')::integer)
  )
  SELECT jsonb_build_object(
    'activeCount', (SELECT count(*) FROM filtered WHERE status = 'active'),
    'bySeverity', COALESCE((SELECT jsonb_object_agg(severity, count) FROM (SELECT severity, count(*) count FROM filtered WHERE status='active' GROUP BY severity) x), '{}'::jsonb),
    'items', COALESCE((SELECT jsonb_agg(to_jsonb(f) - 'raw_payload' ORDER BY raised_at DESC) FROM (SELECT * FROM filtered LIMIT 500) f), '[]'::jsonb)
  );
$$;

CREATE OR REPLACE FUNCTION public.solar_get_data_health(p_from timestamptz DEFAULT now() - interval '24 hours')
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN NOT solar_has_access() THEN NULL ELSE jsonb_build_object(
    'lastSuccessfulSync', (SELECT max(finished_at) FROM huawei_sync_runs WHERE status = 'success'),
    'failedRuns', (SELECT count(*) FROM huawei_sync_runs WHERE started_at >= p_from AND status IN ('failed','dead_letter')),
    'rateLimitIncidents', (SELECT count(*) FROM huawei_sync_runs WHERE started_at >= p_from AND fail_code IN ('407','429')),
    'queueBacklog', (SELECT count(*) FROM huawei_sync_jobs WHERE status IN ('pending','retrying')),
    'deadLetterCount', (SELECT count(*) FROM huawei_sync_jobs WHERE status = 'dead_letter'),
    'stalePlants', (SELECT count(*) FROM huawei_plants p WHERE visible_in_dashboard AND (last_synced_at IS NULL OR last_synced_at < now() - interval '15 minutes')),
    'openQualityIssues', (SELECT count(*) FROM huawei_data_quality_issues WHERE resolved_at IS NULL),
    'qualityByType', COALESCE((SELECT jsonb_object_agg(issue_type, count) FROM (
      SELECT issue_type, count(*) count FROM huawei_data_quality_issues WHERE resolved_at IS NULL GROUP BY issue_type
    ) q), '{}'::jsonb),
    'recentRuns', COALESCE((SELECT jsonb_agg(to_jsonb(r) ORDER BY started_at DESC) FROM (SELECT * FROM huawei_sync_runs ORDER BY started_at DESC LIMIT 100) r), '[]'::jsonb)
  ) END;
$$;

CREATE OR REPLACE FUNCTION public.solar_get_customer_mapping_candidates(p_plant_id uuid)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN NOT solar_is_admin() THEN '[]'::jsonb ELSE COALESCE(jsonb_agg(to_jsonb(x)), '[]'::jsonb) END
  FROM (
    SELECT cs.id, cs.customer_group, cs.province, cs.district, cs.capacity_kw,
      (
        CASE WHEN lower(cs.customer_group) = lower(p.plant_name) THEN 50 ELSE 0 END +
        CASE WHEN cs.province = p.province THEN 25 ELSE 0 END +
        CASE WHEN cs.capacity_kw IS NOT NULL AND p.capacity_kwp IS NOT NULL
          AND abs(cs.capacity_kw - p.capacity_kwp) <= greatest(1, p.capacity_kwp * 0.1) THEN 25 ELSE 0 END
      ) AS match_score
    FROM huawei_plants p CROSS JOIN customer_services cs
    LEFT JOIN huawei_plant_customer_links l ON l.customer_service_id = cs.id
    WHERE p.id = p_plant_id AND l.customer_service_id IS NULL
    ORDER BY match_score DESC, cs.customer_group
    LIMIT 20
  ) x;
$$;

CREATE OR REPLACE FUNCTION public.solar_confirm_customer_mapping(p_plant_id uuid, p_customer_service_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT solar_is_admin() THEN RAISE EXCEPTION 'Forbidden'; END IF;
  INSERT INTO huawei_plant_customer_links (plant_id, customer_service_id, match_status, confirmed_by, confirmed_at)
  VALUES (p_plant_id, p_customer_service_id, 'confirmed', auth.uid(), now())
  ON CONFLICT (plant_id) DO UPDATE SET customer_service_id = excluded.customer_service_id,
    match_status = 'confirmed', confirmed_by = auth.uid(), confirmed_at = now(), updated_at = now();
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.solar_set_tariff(
  p_plant_id uuid, p_name text, p_import_rate numeric, p_export_rate numeric,
  p_valid_from date, p_valid_to date DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_id uuid;
BEGIN
  IF NOT solar_is_admin() THEN RAISE EXCEPTION 'Forbidden'; END IF;
  INSERT INTO huawei_tariffs (
    plant_id, name, import_rate_per_kwh, export_rate_per_kwh, valid_from, valid_to,
    confirmed_by, confirmed_at
  ) VALUES (
    p_plant_id, p_name, p_import_rate, p_export_rate, p_valid_from, p_valid_to,
    auth.uid(), now()
  )
  ON CONFLICT (plant_id, valid_from) DO UPDATE SET
    name = excluded.name, import_rate_per_kwh = excluded.import_rate_per_kwh,
    export_rate_per_kwh = excluded.export_rate_per_kwh, valid_to = excluded.valid_to,
    confirmed_by = auth.uid(), confirmed_at = now(), updated_at = now()
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

REVOKE ALL ON public.huawei_api_sessions FROM anon, authenticated;
REVOKE ALL ON public.huawei_sync_jobs FROM anon;
GRANT EXECUTE ON FUNCTION public.solar_has_access() TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_get_fleet_summary(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_get_plant_list(jsonb,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_get_plant_detail(uuid,timestamptz,timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_get_device_detail(uuid,timestamptz,timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_get_alarm_summary(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_get_data_health(timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_get_customer_mapping_candidates(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_confirm_customer_mapping(uuid,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.solar_set_tariff(uuid,text,numeric,numeric,date,date) TO authenticated;
REVOKE ALL ON FUNCTION public.solar_claim_sync_job(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.solar_claim_sync_job(text) TO service_role;
REVOKE ALL ON FUNCTION public.solar_lock_huawei_login(uuid,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.solar_release_huawei_login(uuid,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.solar_lock_huawei_login(uuid,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.solar_release_huawei_login(uuid,text) TO service_role;
REVOKE ALL ON FUNCTION public.solar_refresh_data_quality(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.solar_refresh_data_quality(uuid) TO service_role;

INSERT INTO public.huawei_integrations (name, base_url, enabled, sync_mode, pilot_plant_limit)
SELECT 'Huawei SmartPVMS SG5', 'https://sg5.fusionsolar.huawei.com', false, 'pilot', 5
WHERE NOT EXISTS (SELECT 1 FROM public.huawei_integrations);

COMMIT;
