// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// In test/dev environments some unit tests import pure utils that transitively
// import this file. Use safe placeholders when env vars are absent so tests can
// run without real Supabase credentials.
const FALLBACK_SUPABASE_URL = 'http://127.0.0.1:54321';
const FALLBACK_SUPABASE_ANON_KEY = 'test-anon-key';

const resolvedSupabaseUrl = SUPABASE_URL || FALLBACK_SUPABASE_URL;
const resolvedSupabaseAnonKey = SUPABASE_ANON_KEY || FALLBACK_SUPABASE_ANON_KEY;

export const supabase = createClient<Database>(resolvedSupabaseUrl, resolvedSupabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // เพิ่มการจัดการ rate limiting
    flowType: 'pkce',
    // ลดความถี่ในการ refresh token
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'sb-auth-token',
    // เพิ่ม timeout สำหรับ refresh token
    debug: false
  },
  global: {
    headers: {
      'X-Client-Info': 'ev-power-energy-crm'
    }
  },
  // เพิ่ม timeout configuration
  db: {
    schema: 'public'
  },
  // เพิ่ม realtime configuration
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});