// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // เพิ่มการจัดการ rate limiting
    flowType: 'pkce',
    // ลดความถี่ในการ refresh token
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'sb-auth-token',
    // เพิ่ม timeout สำหรับ refresh token
    debug: false
  },
  global: {
    headers: {
      'X-Client-Info': 'ev-power-energy-crm'
    }
  },
  // เพิ่ม timeout configuration
  db: {
    schema: 'public'
  },
  // เพิ่ม realtime configuration
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});